# Generated by Django 3.2.3 on 2021-05-18 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('engine_size', models.CharField(max_length=100)),
                ('horsepower', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(blank=True, choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel')], max_length=20)),
                ('is_hybrid', models.BooleanField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
