# Generated by Django 3.2.3 on 2021-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_dealership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'gasoline'), ('diesel', 'diesel')], default='gasoline', max_length=20),
        ),
    ]
